# Generated by Django 3.0.2 on 2020-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=150)),
                ('q2', models.CharField(max_length=150)),
                ('q3', models.CharField(max_length=150)),
                ('q4', models.CharField(max_length=150)),
                ('q5', models.CharField(max_length=150)),
                ('q6', models.CharField(max_length=150)),
                ('q7', models.CharField(max_length=150)),
                ('q8', models.CharField(max_length=150)),
                ('q9', models.CharField(max_length=150)),
                ('q10', models.CharField(max_length=150)),
            ],
        ),
    ]
